[build-system]
requires = ["uv_build>=0.9.18,<0.10.0"]
build-backend = "uv_build"

[project]
name = "htletterspacer"
version = "1.11"
requires-python = ">=3.14"
description = "HT Letterspacer is a tool for spacing fonts"
license = "GPL-3.0-only"
dependencies = [
    "ufoLib2 >=0.11.1",
    "glyphsLib >= 5.2.0",
]

[dependency-groups]
dev = [
    "ruff",
    "pytest >= 6.1.2",
    "pytest-tldr >= 0.2.2",
    "hypothesis >= 6.6.0",
]
